### ISSUE TITLE
Implement bilateral filter

### ISSUE THREAD

**Issue by jackjansen** [cwi-dis/cwipc_kinect#8]
> Moved over from https://gitlab.com/VRTogether_EU/cwipc/cwipc_kinect/-/issues/33

**Comment by nachoreimat** [comment]
Would be interesting to experiment with adding a bilateral filter to improve the depthmap.

I would suggest to try the implementation explained in this paper: https://www.semanticscholar.org/paper/Depth-image-enhancement-for-Kinect-using-region-and-Chen-Lin/159708887e61fb3aa0843908efa2a77c3d8ac2ba

It seems to use the info on the color image to correct:
* **Color/depth mismatching** (we try to solve this by erosion, but it is not the best solution cause we are removing info instead of correcting it), 
* **hole filling** (caused by shiny or transparent materials), 
* **denoising**. 

So if this actually works we could kill 3 birds one shot :)

![3-Figure4-1](/uploads/57f91ed6fc9a017f8f67bfc1cba7e340/3-Figure4-1.png)

It should be easy to do with OpenCV already available in our pipeline :)

**Comment by jackjansen** [comment]
Unfortunately the code for this was broken, and seems beyond repair.
